import fs from 'fs';
import path from 'path';

// This script generates public/config.js from Vercel Environment Variables
// The VERCEL_PUBLIC_ prefix is a Vercel convention to expose these to the browser

const requiredVars = [
  'VERCEL_PUBLIC_FIREBASE_API_KEY',
  'VERCEL_PUBLIC_FIREBASE_AUTH_DOMAIN',
  'VERCEL_PUBLIC_FIREBASE_DATABASE_URL',
  'VERCEL_PUBLIC_FIREBASE_PROJECT_ID',
  'VERCEL_PUBLIC_FIREBASE_STORAGE_BUCKET',
  'VERCEL_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
  'VERCEL_PUBLIC_FIREBASE_APP_ID',
  'VERCEL_PUBLIC_FIREBASE_MEASUREMENT_ID',
];

for (const v of requiredVars) {
  if (!process.env[v]) {
    console.error(`Error: Missing required environment variable ${v}. Please set it in the Vercel project settings.`);
    process.exit(1); // Exit with an error code to fail the build
  }
}

const config = `// This file is generated by the build script. Do not edit.
const firebaseConfig = {
  apiKey: "${process.env.VERCEL_PUBLIC_FIREBASE_API_KEY}",
  authDomain: "${process.env.VERCEL_PUBLIC_FIREBASE_AUTH_DOMAIN}",
  databaseURL: "${process.env.VERCEL_PUBLIC_FIREBASE_DATABASE_URL}",
  projectId: "${process.env.VERCEL_PUBLIC_FIREBASE_PROJECT_ID}",
  storageBucket: "${process.env.VERCEL_PUBLIC_FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${process.env.VERCEL_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${process.env.VERCEL_PUBLIC_FIREBASE_APP_ID}",
  measurementId: "${process.env.VERCEL_PUBLIC_FIREBASE_MEASUREMENT_ID}"
};
`;

fs.writeFileSync(path.join('public', 'config.js'), config);
console.log('Firebase config generated successfully for Vercel deployment.');